version: '3'

services:
  app:
    image: amogus:prod
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_ACCESS=${JWT_SECRET_ACCESS}
      - JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_PROTOCOL=${SPRING_MAIL_PROTOCOL}
    ports:
      - "8080:8080"
    depends_on:
      - db
    profiles:
      - prod
    logging:
      driver: "loki"
      options:
        loki-url: "http://192.168.2.33:3100/loki/api/v1/push"
        loki-batch-size: "400"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    profiles:
      - prod
    logging:
      driver: "loki"
      options:
        loki-url: "http://192.168.2.33:3100/loki/api/v1/push"
        loki-batch-size: "400"

  test-app:
    image: amogus:test
    environment:
      - DB_URL=jdbc:postgresql://test-db:5432/postgres
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_ACCESS=${JWT_SECRET_ACCESS}
      - JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_PROTOCOL=${SPRING_MAIL_PROTOCOL}
    ports:
      - "8081:8080"
    depends_on:
      - test-db
    profiles:
      - test
    logging:
      driver: "loki"
      options:
        loki-url: "http://192.168.2.33:3100/loki/api/v1/push"
        loki-batch-size: "400"

  test-db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    profiles:
      - test
    logging:
      driver: "loki"
      options:
        loki-url: "http://192.168.2.33:3100/loki/api/v1/push"
        loki-batch-size: "400"

volumes:
  postgres_data_test:
  postgres_data_prod:
